node {

  // config 
  def to = emailextrecipients([
         developers(),
         requestor()
  ])
  
  def SendEmailNotification() {
    
    // set variables
    def subject = "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} ${currentBuild.result}"
    def content = '${JELLY_SCRIPT,template="html"}'

    // send email
    if(to != null && !to.isEmpty()) {
      emailext(body: content, mimeType: 'text/html',
         subject: subject,
         to: to, attachLog: true )
    }
  }

  // job
  try {
    stage('run unit test') {
      println('Run the Unit Test Successfully')
    }
    stage('build') {
      println('Built Successfully')
    }
    stage('post-build') {
      // mark build as successful
      currentBuild.result = "SUCCESSFUL";
      
      SendEmailNotification()
    }
  } catch(e) {
    // mark build as failed
    currentBuild.result = "FAILURE";
   
    SendEmailNotification()

    // mark current build as a failure and throw the error
    throw e;
  }
}
